global:
  scrape_interval: 15s 
scrape_configs:
  - job_name: prometheus
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ['prometheus:9090']
        labels:
          service: prometheus