global:
  scrape_interval: 15s 
scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets: ['deltronfr.mooo.com:9090']
        labels:
          service: prometheus
  
  - job_name: cadvisor
    static_configs:
      - targets: ['deltronfr.mooo.com::8100']
        labels:
          service: cadvisor
